-- 1. Create Members Table (No Auth required for daily check-in)
CREATE TABLE members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'member' CHECK (role IN ('member', 'coach')),
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Trainings Table
CREATE TABLE trainings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  date DATE NOT NULL,
  time TEXT NOT NULL,
  type TEXT CHECK (type IN ('water', 'gym', 'tech', 'race')),
  location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create RSVPs Table
CREATE TABLE rsvps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  training_id BIGINT REFERENCES trainings ON DELETE CASCADE NOT NULL,
  member_id BIGINT REFERENCES members ON DELETE CASCADE NOT NULL,
  status TEXT CHECK (status IN ('attending', 'leave', 'undecided')) NOT NULL,
  reason TEXT,
  boat_side TEXT,
  role TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(training_id, member_id)
);

-- 4. Create Check-ins Table
CREATE TABLE checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES members ON DELETE CASCADE NOT NULL,
  training_id BIGINT REFERENCES trainings ON DELETE SET NULL,
  type TEXT CHECK (type IN ('water', 'gym')),
  photo_url TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: In this simplified model, we disable RLS or set it to Public for ease of use
-- Since it's an internal company tool and doesn't contain sensitive data.
-- If security is needed, we can add a simple PIN check for coaches.

ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE trainings ENABLE ROW LEVEL SECURITY;
ALTER TABLE rsvps ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read for all" ON members FOR SELECT USING (true);
CREATE POLICY "Allow public read for all" ON trainings FOR SELECT USING (true);
CREATE POLICY "Allow public read for all" ON rsvps FOR SELECT USING (true);
CREATE POLICY "Allow public read for all" ON checkins FOR SELECT USING (true);

-- Coaches can modify everything
CREATE POLICY "Allow modifications for everyone in this simple demo" ON members FOR ALL USING (true);
CREATE POLICY "Allow modifications for everyone in this simple demo" ON trainings FOR ALL USING (true);
CREATE POLICY "Allow modifications for everyone in this simple demo" ON rsvps FOR ALL USING (true);
CREATE POLICY "Allow modifications for everyone in this simple demo" ON checkins FOR ALL USING (true);

-- Initial Data - Adding some members for the user
INSERT INTO members (full_name, role) VALUES 
('队长李雷', 'coach'),
('韩梅梅', 'member'),
('张伟', 'member'),
('王大锤', 'member'),
('刘备', 'member'),
('关羽', 'member');
